name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt
      - name: Run Ruff
        run: ruff --format=github .
      - name: Run Tests
        run: pytest
